/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package jenkins

import com.lesfurets.jenkins.unit.BaseRegressionTest
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test

class JenkinsLib extends BaseRegressionTest {

    @BeforeEach
    @Override
    void setUp() throws Exception {
        scriptRoots += 'vars'
        super.setUp()
    }

    @Test
    void returnTrue() {
        callStackPath = 'test-resources/callstacks/'
        def script = loadScript('foo.groovy')
        script.call([:])
        testNonRegression( "returnTrue")
    }
}
